"""Question migration

Revision ID: 480a9d00c6de
Revises: ec7aa79d3525
Create Date: 2025-06-15 21:05:35.267824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480a9d00c6de'
down_revision = 'ec7aa79d3525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.String(length=200), nullable=False),
    sa.Column('options', sa.String(length=250), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('correct_answer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.exam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
